export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  "afghanistan": "AF",
  "albania": "AL",
  "united states": "US",
  "united states of america": "US",
  "usa": "US",
  "us": "US",
  "u s": "US",
  "u s a": "US",
  "the states": "US",
  "united kingdom": "GB",
  "uk": "GB",
  "u k": "GB",
  "great britain": "GB",
  "england": "GB",
  "scotland": "GB",
  "wales": "GB",
  "ireland": "IE",
  "lithuania": "LT",
  "latvia": "LV",
  "estonia": "EE",
  "poland": "PL",
  "ukraine": "UA",
  "portugal": "PT",
  "spain": "ES",
  "italy": "IT",
  "germany": "DE",
  "france": "FR",
  "netherlands": "NL",
  "belgium": "BE",
  "romania": "RO",
  "bulgaria": "BG",
  "turkey": "TR",
  "russia": "RU",
  "kazakhstan": "KZ",
  "uzbekistan": "UZ",
  "kyrgyzstan": "KG",
  "morocco": "MA",
  "tunisia": "TN",
  "algeria": "DZ",
  "egypt": "EG",
  "philippines": "PH",
  "india": "IN",
  "pakistan": "PK",
  "bangladesh": "BD",
  "sri lanka": "LK",
  "nepal": "NP",
  "brazil": "BR",
  "mexico": "MX",
  "canada": "CA",
  "australia": "AU",
  "sweden": "SE",
  "norway": "NO",
  "finland": "FI",
  "denmark": "DK",
  "austria": "AT",
  "switzerland": "CH",
  "czech republic": "CZ",
  "czechia": "CZ",
  "slovakia": "SK",
  "hungary": "HU",
  "greece": "GR",
  "croatia": "HR",
  "serbia": "RS",
  "georgia": "GE",
  "armenia": "AM",
  "azerbaijan": "AZ",
  "saudi arabia": "SA",
  "united arab emirates": "AE",
  "uae": "AE",
  "u a e": "AE",
  "qatar": "QA",
  "kuwait": "KW",
  "china": "CN",
  "japan": "JP",
  "south korea": "KR",
  "korea": "KR",
  "vietnam": "VN",
  "thailand": "TH",
  "singapore": "SG",
  "malaysia": "MY",
  "indonesia": "ID",
  "israel": "IL",
  "palestine": "PS",
  "andorra": "AD",
  "angola": "AO",
  "argentina": "AR",
  "bahamas": "BS",
  "bahrain": "BH",
  "belarus": "BY",
  "belize": "BZ",
  "bolivia": "BO",
  "bosnia and herzegovina": "BA",
  "cambodia": "KH",
  "cameroon": "CM",
  "chile": "CL",
  "colombia": "CO",
  "costa rica": "CR",
  "cyprus": "CY",
  "dominican republic": "DO",
  "ecuador": "EC",
  "ghana": "GH",
  "iceland": "IS",
  "jamaica": "JM",
  "jordan": "JO",
  "kenya": "KE",
  "lebanon": "LB",
  "liechtenstein": "LI",
  "luxembourg": "LU",
  "maldives": "MV",
  "malta": "MT",
  "moldova": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "new zealand": "NZ",
  "nigeria": "NG",
  "north macedonia": "MK",
  "panama": "PA",
  "peru": "PE",
  "slovenia": "SI",
  "south africa": "ZA",
  "tajikistan": "TJ",
  "turkmenistan": "TM",
};

export const COUNTRY_OPTIONS = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BR", name: "Brazil" },
  { code: "BG", name: "Bulgaria" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croatia" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "EE", name: "Estonia" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "Mexico" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "RS", name: "Serbia" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "ZA", name: "South Africa" },
  { code: "KR", name: "South Korea" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TH", name: "Thailand" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VN", name: "Vietnam" },
] as const;

const normalizeCountry = (value: string) =>
  value
    .toLowerCase()
    .replace(/\([^)]*\)/g, " ")
    .replace(/[^a-z]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");

const isAlpha2 = (value: string) => /^[a-z]{2}$/i.test(value);

export const toFlagEmoji = (code: string) => {
  if (!isAlpha2(code)) return "";
  const upper = code.toUpperCase();
  return String.fromCodePoint(
    ...upper.split("").map((char) => 127397 + char.charCodeAt(0))
  );
};

const COUNTRY_DISPLAY_NAMES =
  typeof Intl !== "undefined" ? new Intl.DisplayNames(["en"], { type: "region" }) : null;

export function getCountryCode(country?: string | null): string | null {
  if (!country) return null;
  const trimmed = country.trim();
  if (!trimmed) return null;
  const normalized = normalizeCountry(trimmed);
  if (isAlpha2(trimmed)) return trimmed.toUpperCase();
  return COUNTRY_NAME_TO_CODE[normalized] ?? null;
}

export function canonicalizeCountry(country?: string | null): string | null {
  if (!country) return null;
  const code = getCountryCode(country);
  if (!code) return null;
  return COUNTRY_DISPLAY_NAMES?.of(code) ?? country.trim();
}

export type CountryDisplay = {
  label: string;
  flag: string;
};

export function getCountryDisplay(country?: string | null): CountryDisplay {
  if (!country) return { label: "—", flag: "" };
  const trimmed = country.trim();
  if (!trimmed) return { label: "—", flag: "" };
  const code = getCountryCode(trimmed) ?? "";
  return {
    label: trimmed,
    flag: code ? toFlagEmoji(code) : "",
  };
}
